# 판다스 연습문제 풀면서 익숙해지기

In [ ]:
import pandas as pd
import numpy as np


df = pd.DataFrame({
    "name": ["A", "B", "C", "D", "E", "F", "G"],
    "sector": ["AI", "AI", "Web", "Web", "Data", "Data", "AI"],
    "price": [10000, 15000, 8000, 12000, 20000, 18000, 13000],
    "sales": [5, 3, 10, 7, 2, 4, 6],
    "rating": [4.5, 4.0, 3.8, 4.2, 4.9, np.nan, 4.1]
})

In [3]:
print(df.head(5))

  name sector  price  sales  rating
0    A     AI  10000      5     4.5
1    B     AI  15000      3     4.0
2    C    Web   8000     10     3.8
3    D    Web  12000      7     4.2
4    E   Data  20000      2     4.9

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    7 non-null      str
 1   sector  7 non-null      str
 2   price   7 non-null      int64
 3   sales   7 non-null      int64
 4   rating  6 non-null      float64
dtypes: float64(1), int64(2), str(2)
memory usage: 412.0 bytes

In [8]:
df.describe()

              price      sales  rating
count      7.000000   7.000000  6.0000
mean   13714.285714   5.285714  4.2500
std     4270.608298   2.690371  0.3937
min     8000.000000   2.000000  3.8000
25%    11000.000000   3.500000  4.0250
50%    13000.000000   5.000000  4.1500
75%    16500.000000   6.500000  4.4250
max    20000.000000  10.000000  4.9000

In [10]:
print(df[["name","price", "rating"]])

  name  price  rating
0    A  10000     4.5
1    B  15000     4.0
2    C   8000     3.8
3    D  12000     4.2
4    E  20000     4.9
5    F  18000     NaN
6    G  13000     4.1

In [12]:
print(df[df["price"] > 12000])

  name sector  price  sales  rating
1    B     AI  15000      3     4.0
4    E   Data  20000      2     4.9
5    F   Data  18000      4     NaN
6    G     AI  13000      6     4.1

In [14]:
print(df[(df["sector"].eq("AI")) &  (df["price"] > 12000)])

  name sector  price  sales  rating
1    B     AI  15000      3     4.0
6    G     AI  13000      6     4.1

In [18]:
df["total"] = df["price"] * df["sales"]
df

  name sector  price  sales  rating  total
0    A     AI  10000      5     4.5  50000
1    B     AI  15000      3     4.0  45000
2    C    Web   8000     10     3.8  80000
3    D    Web  12000      7     4.2  84000
4    E   Data  20000      2     4.9  40000
5    F   Data  18000      4     NaN  72000
6    G     AI  13000      6     4.1  78000

In [20]:
print(df.sort_values(by="total", ascending=False))

  name sector  price  sales  rating  total
3    D    Web  12000      7     4.2  84000
2    C    Web   8000     10     3.8  80000
6    G     AI  13000      6     4.1  78000
5    F   Data  18000      4     NaN  72000
0    A     AI  10000      5     4.5  50000
1    B     AI  15000      3     4.0  45000
4    E   Data  20000      2     4.9  40000

In [25]:
print(df.groupby(by=["sector"])["price"].agg("mean"))

sector
AI      12666.666667
Data    19000.000000
Web     10000.000000
Name: price, dtype: float64

In [29]:
print(df.groupby("sector")["sales"].mean())

sector
AI      4.666667
Data    3.000000
Web     8.500000
Name: sales, dtype: float64

In [32]:
print(df.groupby(["sector"])[["price", "sales", "rating"]].agg({
  "price": "mean", 
  "sales": "sum", 
  "rating": "mean"
}))

               price  sales  rating
sector
AI      12666.666667     14     4.2
Data    19000.000000      6     4.9
Web     10000.000000     17     4.0

In [34]:
print(np.argwhere(df["rating"].isna()))

[[5]]

In [39]:
df["rating"].fillna(df["rating"].mean())

0    4.50
1    4.00
2    3.80
3    4.20
4    4.90
5    4.25
6    4.10
Name: rating, dtype: float64

In [40]:
df["grade"] = np.where(df["rating"]>=4.2, "good", "normal")

In [42]:
df

  name sector  price  sales  rating  total   grade
0    A     AI  10000      5     4.5  50000    good
1    B     AI  15000      3     4.0  45000  normal
2    C    Web   8000     10     3.8  80000  normal
3    D    Web  12000      7     4.2  84000    good
4    E   Data  20000      2     4.9  40000    good
5    F   Data  18000      4     NaN  72000  normal
6    G     AI  13000      6     4.1  78000  normal

In [52]:
print(df.loc[df["total"].idxmax()])

name          D
sector      Web
price     12000
sales         7
rating      4.2
total     84000
grade      good
Name: 3, dtype: object

In [51]:
print(df.groupby("sector")["total"].sum().sort_values(ascending=False))

sector
AI      173000
Web     164000
Data    112000
Name: total, dtype: int64