In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "name": ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
    "sector": ["AI", "AI", "Web", "Web", "Data", "Data", "AI", "Web", "Data", "AI"],
    "level": ["junior", "senior", "junior", "middle", "senior", "junior", "middle", "senior", "middle", "junior"],
    "price": [10000, 15000, 8000, 12000, 20000, 18000, 13000, 9000, 22000, 11000],
    "sales": [5, 3, 10, 7, 2, 4, 6, 9, 1, 8],
    "rating": [4.5, 4.0, 3.8, 4.2, 4.9, np.nan, 4.1, 3.5, 4.8, np.nan]
})

df["total"] = df["price"] * df["sales"]

In [2]:
df

  name sector   level  price  sales  rating  total
0    A     AI  junior  10000      5     4.5  50000
1    B     AI  senior  15000      3     4.0  45000
2    C    Web  junior   8000     10     3.8  80000
3    D    Web  middle  12000      7     4.2  84000
4    E   Data  senior  20000      2     4.9  40000
5    F   Data  junior  18000      4     NaN  72000
6    G     AI  middle  13000      6     4.1  78000
7    H    Web  senior   9000      9     3.5  81000
8    I   Data  middle  22000      1     4.8  22000
9    J     AI  junior  11000      8     NaN  88000

In [3]:
print(df.columns.value_counts().sum())
print(df.shape[1])
print(df.shape[0])

7
7
10

In [4]:
print(df.columns.tolist())

['name', 'sector', 'level', 'price', 'sales', 'rating', 'total']

In [5]:
print(df.index)

RangeIndex(start=0, stop=10, step=1)

In [6]:
print(df.loc[3])

name           D
sector       Web
level     middle
price      12000
sales          7
rating       4.2
total      84000
Name: 3, dtype: object

In [7]:
print(df.iloc[2])

name           C
sector       Web
level     junior
price       8000
sales         10
rating       3.8
total      80000
Name: 2, dtype: object

In [8]:
print(df.loc[2:6, ["name", "sector", "price"]])

  name sector  price
2    C    Web   8000
3    D    Web  12000
4    E   Data  20000
5    F   Data  18000
6    G     AI  13000

In [9]:
print(df.iloc[0:5, 0:4])

  name sector   level  price
0    A     AI  junior  10000
1    B     AI  senior  15000
2    C    Web  junior   8000
3    D    Web  middle  12000
4    E   Data  senior  20000

In [10]:
df

  name sector   level  price  sales  rating  total
0    A     AI  junior  10000      5     4.5  50000
1    B     AI  senior  15000      3     4.0  45000
2    C    Web  junior   8000     10     3.8  80000
3    D    Web  middle  12000      7     4.2  84000
4    E   Data  senior  20000      2     4.9  40000
5    F   Data  junior  18000      4     NaN  72000
6    G     AI  middle  13000      6     4.1  78000
7    H    Web  senior   9000      9     3.5  81000
8    I   Data  middle  22000      1     4.8  22000
9    J     AI  junior  11000      8     NaN  88000

In [11]:
print(df[df["sector"].isin(["AI", "Data"])])

  name sector   level  price  sales  rating  total
0    A     AI  junior  10000      5     4.5  50000
1    B     AI  senior  15000      3     4.0  45000
4    E   Data  senior  20000      2     4.9  40000
5    F   Data  junior  18000      4     NaN  72000
6    G     AI  middle  13000      6     4.1  78000
8    I   Data  middle  22000      1     4.8  22000
9    J     AI  junior  11000      8     NaN  88000

In [12]:
print(df[df["price"].between(10000, 18000)])

  name sector   level  price  sales  rating  total
0    A     AI  junior  10000      5     4.5  50000
1    B     AI  senior  15000      3     4.0  45000
3    D    Web  middle  12000      7     4.2  84000
5    F   Data  junior  18000      4     NaN  72000
6    G     AI  middle  13000      6     4.1  78000
9    J     AI  junior  11000      8     NaN  88000

In [13]:
print(df[df["rating"].notna()])
# df["rating"].notna()

  name sector   level  price  sales  rating  total
0    A     AI  junior  10000      5     4.5  50000
1    B     AI  senior  15000      3     4.0  45000
2    C    Web  junior   8000     10     3.8  80000
3    D    Web  middle  12000      7     4.2  84000
4    E   Data  senior  20000      2     4.9  40000
6    G     AI  middle  13000      6     4.1  78000
7    H    Web  senior   9000      9     3.5  81000
8    I   Data  middle  22000      1     4.8  22000

In [14]:
print(df["sector"].value_counts())

sector
AI      4
Web     3
Data    3
Name: count, dtype: int64

In [15]:
print(df["level"].value_counts())

level
junior    4
senior    3
middle    3
Name: count, dtype: int64

In [16]:
print(df.groupby("sector")["total"].sum().sort_values(ascending=False))

sector
AI      261000
Web     245000
Data    134000
Name: total, dtype: int64

In [17]:
print(df.groupby(["sector", "price"])["price"].mean())

sector  price
AI      10000    10000.0
        11000    11000.0
        13000    13000.0
        15000    15000.0
Data    18000    18000.0
        20000    20000.0
        22000    22000.0
Web     8000      8000.0
        9000      9000.0
        12000    12000.0
Name: price, dtype: float64

In [18]:
print(df.groupby(["sector"]).agg({
  "price": "mean",
  "sales": "sum",
  "rating": "sum",
  "total": "sum"
}))
df

               price  sales  rating   total
sector
AI      12250.000000     22    12.6  261000
Data    20000.000000      7     9.7  134000
Web      9666.666667     26    11.5  245000

  name sector   level  price  sales  rating  total
0    A     AI  junior  10000      5     4.5  50000
1    B     AI  senior  15000      3     4.0  45000
2    C    Web  junior   8000     10     3.8  80000
3    D    Web  middle  12000      7     4.2  84000
4    E   Data  senior  20000      2     4.9  40000
5    F   Data  junior  18000      4     NaN  72000
6    G     AI  middle  13000      6     4.1  78000
7    H    Web  senior   9000      9     3.5  81000
8    I   Data  middle  22000      1     4.8  22000
9    J     AI  junior  11000      8     NaN  88000

In [19]:
# df

df["rating_fillna"] = df["rating"].fillna(df.groupby("sector")["rating"].transform("mean"))
print(df)
# 16번 모르겠음

  name sector   level  price  sales  rating  total  rating_fillna
0    A     AI  junior  10000      5     4.5  50000           4.50
1    B     AI  senior  15000      3     4.0  45000           4.00
2    C    Web  junior   8000     10     3.8  80000           3.80
3    D    Web  middle  12000      7     4.2  84000           4.20
4    E   Data  senior  20000      2     4.9  40000           4.90
5    F   Data  junior  18000      4     NaN  72000           4.85
6    G     AI  middle  13000      6     4.1  78000           4.10
7    H    Web  senior   9000      9     3.5  81000           3.50
8    I   Data  middle  22000      1     4.8  22000           4.80
9    J     AI  junior  11000      8     NaN  88000           4.20