In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105, 105, 106, 107, 108, 109, 110],
    "customer": [" kim ", "LEE", "park", "Choi", "kim", "kim", "lee ", "PARK", "choi", "Han", "han "],
    "category": ["AI course", "web course", "data course", "AI course", "web course", "web course", "data course", "AI course", "web course", np.nan, "Data Course"],
    "price": [100000, 80000, 120000, np.nan, 90000, 90000, 110000, 150000, 70000, 60000, 60000],
    "quantity": [1, 2, 1, 1, 3, 3, np.nan, 1, 2, 1, 1],
    "status": ["paid", "paid", "cancelled", "paid", "paid", "paid", "cancelled", "paid", "pending", "paid", "paid"]
})

In [3]:
df

    order_id customer     category     price  quantity     status
0        101     kim     AI course  100000.0       1.0       paid
1        102      LEE   web course   80000.0       2.0       paid
2        103     park  data course  120000.0       1.0  cancelled
3        104     Choi    AI course       NaN       1.0       paid
4        105      kim   web course   90000.0       3.0       paid
5        105      kim   web course   90000.0       3.0       paid
6        106     lee   data course  110000.0       NaN  cancelled
7        107     PARK    AI course  150000.0       1.0       paid
8        108     choi   web course   70000.0       2.0    pending
9        109      Han          NaN   60000.0       1.0       paid
10       110     han   Data Course   60000.0       1.0       paid

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  11 non-null     int64
 1   customer  11 non-null     str
 2   category  10 non-null     str
 3   price     10 non-null     float64
 4   quantity  10 non-null     float64
 5   status    11 non-null     str
dtypes: float64(2), int64(1), str(3)
memory usage: 660.0 bytes

In [7]:
df.isna().sum()

order_id    0
customer    0
category    1
price       1
quantity    1
status      0
dtype: int64

In [14]:
print(np.where(df.duplicated())[0])
print(np.where(df.duplicated(subset="order_id"))[0])

[5]
[5]

In [16]:
print(df.drop_duplicates(subset="order_id"))

df_clean = df.drop_duplicates(subset="order_id")

    order_id customer     category     price  quantity     status
0        101     kim     AI course  100000.0       1.0       paid
1        102      LEE   web course   80000.0       2.0       paid
2        103     park  data course  120000.0       1.0  cancelled
3        104     Choi    AI course       NaN       1.0       paid
4        105      kim   web course   90000.0       3.0       paid
6        106     lee   data course  110000.0       NaN  cancelled
7        107     PARK    AI course  150000.0       1.0       paid
8        108     choi   web course   70000.0       2.0    pending
9        109      Han          NaN   60000.0       1.0       paid
10       110     han   Data Course   60000.0       1.0       paid

In [ ]:
df["customer"] = df["customer"].str.strip().str.lower()

In [22]:
df

    order_id customer     category     price  quantity     status
0        101      kim    AI course  100000.0       1.0       paid
1        102      lee   web course   80000.0       2.0       paid
2        103     park  data course  120000.0       1.0  cancelled
3        104     choi    AI course       NaN       1.0       paid
4        105      kim   web course   90000.0       3.0       paid
5        105      kim   web course   90000.0       3.0       paid
6        106      lee  data course  110000.0       NaN  cancelled
7        107     park    AI course  150000.0       1.0       paid
8        108     choi   web course   70000.0       2.0    pending
9        109      han          NaN   60000.0       1.0       paid
10       110      han  Data Course   60000.0       1.0       paid

In [24]:
print(df[df["category"].isna()])

   order_id customer category    price  quantity status
9       109      han      NaN  60000.0       1.0   paid

In [27]:
df["category"] = df["category"].fillna("unknown")
df

    order_id customer     category     price  quantity     status
0        101      kim    AI course  100000.0       1.0       paid
1        102      lee   web course   80000.0       2.0       paid
2        103     park  data course  120000.0       1.0  cancelled
3        104     choi    AI course       NaN       1.0       paid
4        105      kim   web course   90000.0       3.0       paid
5        105      kim   web course   90000.0       3.0       paid
6        106      lee  data course  110000.0       NaN  cancelled
7        107     park    AI course  150000.0       1.0       paid
8        108     choi   web course   70000.0       2.0    pending
9        109      han      unknown   60000.0       1.0       paid
10       110      han  Data Course   60000.0       1.0       paid

In [30]:
df["price"] = df["price"].fillna(df["price"].mean())
df

    order_id customer     category     price  quantity     status
0        101      kim    AI course  100000.0       1.0       paid
1        102      lee   web course   80000.0       2.0       paid
2        103     park  data course  120000.0       1.0  cancelled
3        104     choi    AI course   93000.0       1.0       paid
4        105      kim   web course   90000.0       3.0       paid
5        105      kim   web course   90000.0       3.0       paid
6        106      lee  data course  110000.0       NaN  cancelled
7        107     park    AI course  150000.0       1.0       paid
8        108     choi   web course   70000.0       2.0    pending
9        109      han      unknown   60000.0       1.0       paid
10       110      han  Data Course   60000.0       1.0       paid

In [32]:
df["quantity"] = df["quantity"].fillna(1)

In [33]:
df["total"] = df["price"]*df["quantity"]
df

    order_id customer     category     price  quantity     status     total
0        101      kim    AI course  100000.0       1.0       paid  100000.0
1        102      lee   web course   80000.0       2.0       paid  160000.0
2        103     park  data course  120000.0       1.0  cancelled  120000.0
3        104     choi    AI course   93000.0       1.0       paid   93000.0
4        105      kim   web course   90000.0       3.0       paid  270000.0
5        105      kim   web course   90000.0       3.0       paid  270000.0
6        106      lee  data course  110000.0       1.0  cancelled  110000.0
7        107     park    AI course  150000.0       1.0       paid  150000.0
8        108     choi   web course   70000.0       2.0    pending  140000.0
9        109      han      unknown   60000.0       1.0       paid   60000.0
10       110      han  Data Course   60000.0       1.0       paid   60000.0

In [34]:
df_valid = df[df["status"].eq("cancelled")]
print(df_valid)

   order_id customer     category     price  quantity     status     total
2       103     park  data course  120000.0       1.0  cancelled  120000.0
6       106      lee  data course  110000.0       1.0  cancelled  110000.0

In [36]:
print(df[df["category"].str.contains("course", na=False)])

   order_id customer     category     price  quantity     status     total
0       101      kim    AI course  100000.0       1.0       paid  100000.0
1       102      lee   web course   80000.0       2.0       paid  160000.0
2       103     park  data course  120000.0       1.0  cancelled  120000.0
3       104     choi    AI course   93000.0       1.0       paid   93000.0
4       105      kim   web course   90000.0       3.0       paid  270000.0
5       105      kim   web course   90000.0       3.0       paid  270000.0
6       106      lee  data course  110000.0       1.0  cancelled  110000.0
7       107     park    AI course  150000.0       1.0       paid  150000.0
8       108     choi   web course   70000.0       2.0    pending  140000.0

In [42]:
df["category_simple"] = df["category"].str.replace("course", "").str.strip()
df

,order_id,customer,category,price,quantity,status,total,category_simple
0,101,kim,AI course,100000.0,1.0,paid,100000.0,AI
1,102,lee,web course,80000.0,2.0,paid,160000.0,web
2,103,park,data course,120000.0,1.0,cancelled,120000.0,data
3,104,choi,AI course,93000.0,1.0,paid,93000.0,AI
4,105,kim,web course,90000.0,3.0,paid,270000.0,web
5,105,kim,web course,90000.0,3.0,paid,270000.0,web
6,106,lee,data course,110000.0,1.0,cancelled,110000.0,data
7,107,park,AI course,150000.0,1.0,paid,150000.0,AI
8,108,choi,web course,70000.0,2.0,pending,140000.0,web
9,109,han,unknown,60000.0,1.0,paid,60000.0,unknown
10,110,han,Data Course,60000.0,1.0,paid,60000.0,Data Course

In [44]:
print(df.groupby("customer")["total"].sum())

customer
choi    233000.0
han     120000.0
kim     640000.0
lee     270000.0
park    270000.0
Name: total, dtype: float64

In [47]:
print(df.groupby("category_simple")[["price", "quantity", "total"]].agg({
  "price": "mean",
  "quantity": "sum",
  "total": "sum"
}))

                         price  quantity     total
category_simple
AI               114333.333333       3.0  343000.0
Data Course       60000.000000       1.0   60000.0
data             115000.000000       2.0  230000.0
unknown           60000.000000       1.0   60000.0
web               82500.000000      10.0  840000.0

In [ ]:
# df.columns[df.columns.get_loc("customer")] = "customer_name"
# df.columns.set
df.columns = df.columns.str.replace("customer", "customer_name")
df

,order_id,customer_name,category,price,quantity,status,total,category_simple
0,101,kim,AI course,100000.0,1.0,paid,100000.0,AI
1,102,lee,web course,80000.0,2.0,paid,160000.0,web
2,103,park,data course,120000.0,1.0,cancelled,120000.0,data
3,104,choi,AI course,93000.0,1.0,paid,93000.0,AI
4,105,kim,web course,90000.0,3.0,paid,270000.0,web
5,105,kim,web course,90000.0,3.0,paid,270000.0,web
6,106,lee,data course,110000.0,1.0,cancelled,110000.0,data
7,107,park,AI course,150000.0,1.0,paid,150000.0,AI
8,108,choi,web course,70000.0,2.0,pending,140000.0,web
9,109,han,unknown,60000.0,1.0,paid,60000.0,unknown
10,110,han,Data Course,60000.0,1.0,paid,60000.0,Data Course

In [ ]:
df["status"] = df["status"].str.replace({
  "paid": "complete",
  "pending": "waiting",
  "cancelled": "cancelled"
})

df

,order_id,customer_name,category,price,quantity,status,total,category_simple
0,101,kim,AI course,100000.0,1.0,complete,100000.0,AI
1,102,lee,web course,80000.0,2.0,complete,160000.0,web
2,103,park,data course,120000.0,1.0,cancelled,120000.0,data
3,104,choi,AI course,93000.0,1.0,complete,93000.0,AI
4,105,kim,web course,90000.0,3.0,complete,270000.0,web
5,105,kim,web course,90000.0,3.0,complete,270000.0,web
6,106,lee,data course,110000.0,1.0,cancelled,110000.0,data
7,107,park,AI course,150000.0,1.0,complete,150000.0,AI
8,108,choi,web course,70000.0,2.0,waiting,140000.0,web
9,109,han,unknown,60000.0,1.0,complete,60000.0,unknown
10,110,han,Data Course,60000.0,1.0,complete,60000.0,Data Course

: