In [ ]:
import pandas as pd
import numpy as np

orders = pd.DataFrame({
    "order_id": [
        "A001", "A002", "A003", "A004", "A005", "A006",
        "A007", "A008", "A009", "A010", "A011", "A012",
        "A013", "A014", "A015", "A016", "A017", "A018"
    ],
    "customer_id": [
        "C01", "C02", "C01", "C03", "C04", "C02",
        "C05", "C03", "C06", "C01", "C07", "C04",
        "C08", "C02", "C09", "C05", "C10", "C03"
    ],
    "order_date": [
        "2026-01-01", "2026-01-02", "2026-01-05", "2026-01-07",
        "2026-01-08", "2026-01-11", "2026-01-14", "2026-01-15",
        "2026-01-18", "2026-01-22", "2026-01-23", "2026-01-25",
        "2026-01-29", "2026-02-01", "2026-02-03", "2026-02-04",
        "2026-02-07", "2026-02-10"
    ],
    "product": [
        "notebook/pro", "mouse/basic", "keyboard/mechanical", "monitor/27inch",
        "notebook/air", "mouse/gaming", "chair/ergonomic", "monitor/32inch",
        "keyboard/basic", "notebook/pro", "desk/standing", "chair/basic",
        "monitor/27inch", "mouse/basic", "notebook/pro", "desk/normal",
        "keyboard/mechanical", "chair/ergonomic"
    ],
    "category": [
        "PC", "ACC", "ACC", "MONITOR", "PC", "ACC",
        "FURNITURE", "MONITOR", "ACC", "PC", "FURNITURE", "FURNITURE",
        "MONITOR", "ACC", "PC", "FURNITURE", "ACC", "FURNITURE"
    ],
    "quantity": [1, 2, 1, 1, 1, 3, 1, 1, 2, 1, 1, np.nan, 1, 2, 1, 1, 1, 1],
    "price": [
        1500000, 25000, 120000, 330000, 1100000, 55000,
        270000, 490000, 45000, 1520000, 380000, 90000,
        350000, 25000, 5000000, 220000, 130000, 280000
    ],
    "discount_rate": [
        0.05, 0.00, 0.10, 0.05, 0.03, 0.00,
        0.15, 0.07, np.nan, 0.05, 0.20, 0.00,
        0.05, 0.00, 0.50, 0.10, 0.10, 0.15
    ],
    "region": [
        "Seoul", "Busan", "Seoul", "Incheon", "Seoul", "Busan",
        "Daegu", "Incheon", "Seoul", "Seoul", "Busan", "Daegu",
        "Incheon", "Busan", "Seoul", "Daegu", "Seoul", "Incheon"
    ]
})

customers = pd.DataFrame({
    "customer_id": ["C01", "C02", "C03", "C04", "C05", "C06", "C07", "C08", "C11"],
    "grade": ["VIP", "Gold", "Silver", "Gold", "Silver", "Basic", "VIP", "Basic", "Gold"],
    "join_date": [
        "2025-03-01", "2025-07-15", "2025-09-10", "2025-11-20",
        "2025-12-01", "2026-01-01", "2025-01-10", "2026-01-20", "2025-08-08"
    ]
})

In [3]:

print(orders.info())
print(customers.info())

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       18 non-null     str
 1   customer_id    18 non-null     str
 2   order_date     18 non-null     str
 3   product        18 non-null     str
 4   category       18 non-null     str
 5   quantity       17 non-null     float64
 6   price          18 non-null     int64
 7   discount_rate  17 non-null     float64
 8   region         18 non-null     str
dtypes: float64(2), int64(1), str(6)
memory usage: 1.4 KB
None
<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  9 non-null      str
 1   grade        9 non-null      str
 2   join_date    9 non-null      str
dtypes: str(3)
memory usage: 348.0 bytes
None

In [9]:
customers["join_date"] = pd.to_datetime(customers["join_date"])
orders["order_date"] = pd.to_datetime(orders["order_date"])
print(customers.info())
print(orders.info())

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  9 non-null      str
 1   grade        9 non-null      str
 2   join_date    9 non-null      datetime64[us]
dtypes: datetime64[us](1), str(2)
memory usage: 348.0 bytes
None
<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       18 non-null     str
 1   customer_id    18 non-null     str
 2   order_date     18 non-null     datetime64[us]
 3   product        18 non-null     str
 4   category       18 non-null     str
 5   quantity       17 non-null     float64
 6   price          18 non-null     int64
 7   discount_rate  17 non-null     float64
 8   region         18 non-null     str
dtypes: datetime64[us](1), float64(2), int64(1), str(5)
memory usage: 1.4 KB
None

In [10]:
orders.head()

,order_id,customer_id,order_date,product,category,quantity,price,discount_rate,region
0,A001,C01,2026-01-01,notebook/pro,PC,1.0,1500000,0.05,Seoul
1,A002,C02,2026-01-02,mouse/basic,ACC,2.0,25000,0.00,Busan
2,A003,C01,2026-01-05,keyboard/mechanical,ACC,1.0,120000,0.10,Seoul
3,A004,C03,2026-01-07,monitor/27inch,MONITOR,1.0,330000,0.05,Incheon
4,A005,C04,2026-01-08,notebook/air,PC,1.0,1100000,0.03,Seoul

In [ ]:
orders["quantity"] = orders.groupby("category")["quantity"].transform("mean")
orders["quantity"]

0     1.000000
1     1.833333
2     1.833333
3     1.000000
4     1.000000
5     1.833333
6     1.000000
7     1.000000
8     1.833333
9     1.000000
10    1.000000
11    1.000000
12    1.000000
13    1.833333
14    1.000000
15    1.000000
16    1.833333
17    1.000000
Name: quantity, dtype: float64

In [16]:
orders["discount_rate"] = orders["discount_rate"].fillna(0)
orders["discount_rate"]

0     0.05
1     0.00
2     0.10
3     0.05
4     0.03
5     0.00
6     0.15
7     0.07
8     0.00
9     0.05
10    0.20
11    0.00
12    0.05
13    0.00
14    0.50
15    0.10
16    0.10
17    0.15
Name: discount_rate, dtype: float64

In [18]:
orders["product"]

0            notebook/pro
1             mouse/basic
2     keyboard/mechanical
3          monitor/27inch
4            notebook/air
5            mouse/gaming
6         chair/ergonomic
7          monitor/32inch
8          keyboard/basic
9            notebook/pro
10          desk/standing
11            chair/basic
12         monitor/27inch
13            mouse/basic
14           notebook/pro
15            desk/normal
16    keyboard/mechanical
17        chair/ergonomic
Name: product, dtype: str

In [26]:


orders[["product_main", "product_sub"]] = orders["product"].str.split("/", expand=True).iloc[:, [0, -1]].set_axis(["product_main", "product_sub"], axis=1)
orders

,order_id,customer_id,order_date,product,category,quantity,price,discount_rate,region,product_main,product_sub
0,A001,C01,2026-01-01,notebook/pro,PC,1.000000,1500000,0.05,Seoul,notebook,pro
1,A002,C02,2026-01-02,mouse/basic,ACC,1.833333,25000,0.00,Busan,mouse,basic
2,A003,C01,2026-01-05,keyboard/mechanical,ACC,1.833333,120000,0.10,Seoul,keyboard,mechanical
3,A004,C03,2026-01-07,monitor/27inch,MONITOR,1.000000,330000,0.05,Incheon,monitor,27inch
4,A005,C04,2026-01-08,notebook/air,PC,1.000000,1100000,0.03,Seoul,notebook,air
5,A006,C02,2026-01-11,mouse/gaming,ACC,1.833333,55000,0.00,Busan,mouse,gaming
6,A007,C05,2026-01-14,chair/ergonomic,FURNITURE,1.000000,270000,0.15,Daegu,chair,ergonomic
7,A008,C03,2026-01-15,monitor/32inch,MONITOR,1.000000,490000,0.07,Incheon,monitor,32inch
8,A009,C06,2026-01-18,keyboard/basic,ACC,1.833333,45000,0.00,Seoul,keyboard,basic
9,A010,C01,2026-01-22,notebook/pro,PC,1.000000,1520000,0.05,Seoul,notebook,pro
10,A011,C07,2026-01-23,desk/standing,FURNITURE,1.000000,380000,0.20,Busan,desk,standing
11,A012,C04,2026-01-25,chair/basic,FURNITURE,1.000000,90000,0.00,Daegu,chair,basic
12,A013,C08,2026-01-29,monitor/27inch,MONITOR,1.000000,350000,0.05,Incheon,monitor,27inch
13,A014,C02,2026-02-01,mouse/basic,ACC,1.833333,25000,0.00,Busan,mouse,basic
14,A015,C09,2026-02-03,notebook/pro,PC,1.000000,5000000,0.50,Seoul,notebook,pro
15,A016,C05,2026-02-04,desk/normal,FURNITURE,1.000000,220000,0.10,Daegu,desk,normal
16,A017,C10,2026-02-07,keyboard/mechanical,ACC,1.833333,130000,0.10,Seoul,keyboard,mechanical
17,A018,C03,2026-02-10,chair/ergonomic,FURNITURE,1.000000,280000,0.15,Incheon,chair,ergonomic

In [29]:
import datetime

print(orders[orders["order_date"] >= datetime.datetime(2026, 1, 15)])

   order_id customer_id order_date              product   category  quantity  \
7      A008         C03 2026-01-15       monitor/32inch    MONITOR  1.000000
8      A009         C06 2026-01-18       keyboard/basic        ACC  1.833333
9      A010         C01 2026-01-22         notebook/pro         PC  1.000000
10     A011         C07 2026-01-23        desk/standing  FURNITURE  1.000000
11     A012         C04 2026-01-25          chair/basic  FURNITURE  1.000000
12     A013         C08 2026-01-29       monitor/27inch    MONITOR  1.000000
13     A014         C02 2026-02-01          mouse/basic        ACC  1.833333
14     A015         C09 2026-02-03         notebook/pro         PC  1.000000
15     A016         C05 2026-02-04          desk/normal  FURNITURE  1.000000
16     A017         C10 2026-02-07  keyboard/mechanical        ACC  1.833333
17     A018         C03 2026-02-10      chair/ergonomic  FURNITURE  1.000000

      price  discount_rate   region product_main product_sub
7    490000           0.07  Incheon      monitor      32inch
8     45000           0.00    Seoul     keyboard       basic
9   1520000           0.05    Seoul     notebook         pro
10   380000           0.20    Busan         desk    standing
11    90000           0.00    Daegu        chair       basic
12   350000           0.05  Incheon      monitor      27inch
13    25000           0.00    Busan        mouse       basic
14  5000000           0.50    Seoul     notebook         pro
15   220000           0.10    Daegu         desk      normal
16   130000           0.10    Seoul     keyboard  mechanical
17   280000           0.15  Incheon        chair   ergonomic

In [31]:
# 문제 2: 결측치 처리
# orders의 quantity 결측치를 category별 quantity 평균으로 채운 뒤, filled_orders 변수에 저장하세요.
# 힌트: groupby(), transform(), fillna()를 사용해보세요.

# 이미 되어있음.
orders["filled_orders"] = orders["quantity"]
orders

,order_id,customer_id,order_date,product,category,quantity,price,discount_rate,region,product_main,product_sub,filled_orders
0,A001,C01,2026-01-01,notebook/pro,PC,1.000000,1500000,0.05,Seoul,notebook,pro,1.000000
1,A002,C02,2026-01-02,mouse/basic,ACC,1.833333,25000,0.00,Busan,mouse,basic,1.833333
2,A003,C01,2026-01-05,keyboard/mechanical,ACC,1.833333,120000,0.10,Seoul,keyboard,mechanical,1.833333
3,A004,C03,2026-01-07,monitor/27inch,MONITOR,1.000000,330000,0.05,Incheon,monitor,27inch,1.000000
4,A005,C04,2026-01-08,notebook/air,PC,1.000000,1100000,0.03,Seoul,notebook,air,1.000000
5,A006,C02,2026-01-11,mouse/gaming,ACC,1.833333,55000,0.00,Busan,mouse,gaming,1.833333
6,A007,C05,2026-01-14,chair/ergonomic,FURNITURE,1.000000,270000,0.15,Daegu,chair,ergonomic,1.000000
7,A008,C03,2026-01-15,monitor/32inch,MONITOR,1.000000,490000,0.07,Incheon,monitor,32inch,1.000000
8,A009,C06,2026-01-18,keyboard/basic,ACC,1.833333,45000,0.00,Seoul,keyboard,basic,1.833333
9,A010,C01,2026-01-22,notebook/pro,PC,1.000000,1520000,0.05,Seoul,notebook,pro,1.000000
10,A011,C07,2026-01-23,desk/standing,FURNITURE,1.000000,380000,0.20,Busan,desk,standing,1.000000
11,A012,C04,2026-01-25,chair/basic,FURNITURE,1.000000,90000,0.00,Daegu,chair,basic,1.000000
12,A013,C08,2026-01-29,monitor/27inch,MONITOR,1.000000,350000,0.05,Incheon,monitor,27inch,1.000000
13,A014,C02,2026-02-01,mouse/basic,ACC,1.833333,25000,0.00,Busan,mouse,basic,1.833333
14,A015,C09,2026-02-03,notebook/pro,PC,1.000000,5000000,0.50,Seoul,notebook,pro,1.000000
15,A016,C05,2026-02-04,desk/normal,FURNITURE,1.000000,220000,0.10,Daegu,desk,normal,1.000000
16,A017,C10,2026-02-07,keyboard/mechanical,ACC,1.833333,130000,0.10,Seoul,keyboard,mechanical,1.833333
17,A018,C03,2026-02-10,chair/ergonomic,FURNITURE,1.000000,280000,0.15,Incheon,chair,ergonomic,1.000000

In [32]:
# 문제 3: 할인 적용 금액 만들기
# orders에 final_price 컬럼을 추가하세요.
# 계산식: price * quantity * (1 - discount_rate)
# discount_rate 결측치는 0으로 처리한 뒤 계산하세요.

orders["final_price"] = orders["price"] * orders["quantity"] * (1 - orders["discount_rate"])
orders

,order_id,customer_id,order_date,product,category,quantity,price,discount_rate,region,product_main,product_sub,filled_orders,final_price
0,A001,C01,2026-01-01,notebook/pro,PC,1.000000,1500000,0.05,Seoul,notebook,pro,1.000000,1.425000e+06
1,A002,C02,2026-01-02,mouse/basic,ACC,1.833333,25000,0.00,Busan,mouse,basic,1.833333,4.583333e+04
2,A003,C01,2026-01-05,keyboard/mechanical,ACC,1.833333,120000,0.10,Seoul,keyboard,mechanical,1.833333,1.980000e+05
3,A004,C03,2026-01-07,monitor/27inch,MONITOR,1.000000,330000,0.05,Incheon,monitor,27inch,1.000000,3.135000e+05
4,A005,C04,2026-01-08,notebook/air,PC,1.000000,1100000,0.03,Seoul,notebook,air,1.000000,1.067000e+06
5,A006,C02,2026-01-11,mouse/gaming,ACC,1.833333,55000,0.00,Busan,mouse,gaming,1.833333,1.008333e+05
6,A007,C05,2026-01-14,chair/ergonomic,FURNITURE,1.000000,270000,0.15,Daegu,chair,ergonomic,1.000000,2.295000e+05
7,A008,C03,2026-01-15,monitor/32inch,MONITOR,1.000000,490000,0.07,Incheon,monitor,32inch,1.000000,4.557000e+05
8,A009,C06,2026-01-18,keyboard/basic,ACC,1.833333,45000,0.00,Seoul,keyboard,basic,1.833333,8.250000e+04
9,A010,C01,2026-01-22,notebook/pro,PC,1.000000,1520000,0.05,Seoul,notebook,pro,1.000000,1.444000e+06
10,A011,C07,2026-01-23,desk/standing,FURNITURE,1.000000,380000,0.20,Busan,desk,standing,1.000000,3.040000e+05
11,A012,C04,2026-01-25,chair/basic,FURNITURE,1.000000,90000,0.00,Daegu,chair,basic,1.000000,9.000000e+04
12,A013,C08,2026-01-29,monitor/27inch,MONITOR,1.000000,350000,0.05,Incheon,monitor,27inch,1.000000,3.325000e+05
13,A014,C02,2026-02-01,mouse/basic,ACC,1.833333,25000,0.00,Busan,mouse,basic,1.833333,4.583333e+04
14,A015,C09,2026-02-03,notebook/pro,PC,1.000000,5000000,0.50,Seoul,notebook,pro,1.000000,2.500000e+06
15,A016,C05,2026-02-04,desk/normal,FURNITURE,1.000000,220000,0.10,Daegu,desk,normal,1.000000,1.980000e+05
16,A017,C10,2026-02-07,keyboard/mechanical,ACC,1.833333,130000,0.10,Seoul,keyboard,mechanical,1.833333,2.145000e+05
17,A018,C03,2026-02-10,chair/ergonomic,FURNITURE,1.000000,280000,0.15,Incheon,chair,ergonomic,1.000000,2.380000e+05

In [ ]:
# 문제 4: 문자열 분리
# product 컬럼을 '/' 기준으로 나누어 product_main, product_sub 컬럼을 만드세요.
# 예: 'notebook/pro' -> product_main='notebook', product_sub='pro'

# 되어있음

In [33]:
# 문제 5: 카테고리별 매출 집계
# category별 final_price 합계를 구하고, 매출이 큰 순서대로 정렬하세요.
# 결과는 category_sales 변수에 저장하세요.

category_sales = orders.groupby("category")["final_price"].sum()
category_sales

category
ACC           687500.0
FURNITURE    1059500.0
MONITOR      1101700.0
PC           6436000.0
Name: final_price, dtype: float64

In [40]:
# 문제 6: 지역별 주문 수와 평균 결제금액
# region별 주문 수(order_count)와 평균 final_price(avg_final_price)를 구하세요.
# 결과는 region_summary 변수에 저장하세요.

region_summary = orders.groupby("region")["final_price"].agg(["mean", "count"])
# agg({
#   "order_count": "sum",
#   "final_price": "mean"
# })
region_summary

                  mean  count
region
Busan    124125.000000      4
Daegu    172500.000000      3
Incheon  334925.000000      4
Seoul    990142.857143      7

In [66]:
# 문제 7: 고객 정보 합치기
# orders와 customers를 customer_id 기준으로 left merge하세요.
# 결과는 order_customer 변수에 저장하세요.
# 주문에는 있지만 customers에 없는 고객도 사라지면 안 됩니다.

order_customer = pd.merge(orders, customers, how="left", on="customer_id")
order_customer

,order_id,customer_id,order_date,product,category,quantity,price,discount_rate,region,product_main,product_sub,filled_orders,final_price,order_month,grade,join_date
0,A001,C01,2026-01-01,notebook/pro,PC,1.000000,1500000,0.05,Seoul,notebook,pro,1.000000,1.425000e+06,2026-01,VIP,2025-03-01
1,A002,C02,2026-01-02,mouse/basic,ACC,1.833333,25000,0.00,Busan,mouse,basic,1.833333,4.583333e+04,2026-01,Gold,2025-07-15
2,A003,C01,2026-01-05,keyboard/mechanical,ACC,1.833333,120000,0.10,Seoul,keyboard,mechanical,1.833333,1.980000e+05,2026-01,VIP,2025-03-01
3,A004,C03,2026-01-07,monitor/27inch,MONITOR,1.000000,330000,0.05,Incheon,monitor,27inch,1.000000,3.135000e+05,2026-01,Silver,2025-09-10
4,A005,C04,2026-01-08,notebook/air,PC,1.000000,1100000,0.03,Seoul,notebook,air,1.000000,1.067000e+06,2026-01,Gold,2025-11-20
5,A006,C02,2026-01-11,mouse/gaming,ACC,1.833333,55000,0.00,Busan,mouse,gaming,1.833333,1.008333e+05,2026-01,Gold,2025-07-15
6,A007,C05,2026-01-14,chair/ergonomic,FURNITURE,1.000000,270000,0.15,Daegu,chair,ergonomic,1.000000,2.295000e+05,2026-01,Silver,2025-12-01
7,A008,C03,2026-01-15,monitor/32inch,MONITOR,1.000000,490000,0.07,Incheon,monitor,32inch,1.000000,4.557000e+05,2026-01,Silver,2025-09-10
8,A009,C06,2026-01-18,keyboard/basic,ACC,1.833333,45000,0.00,Seoul,keyboard,basic,1.833333,8.250000e+04,2026-01,Basic,2026-01-01
9,A010,C01,2026-01-22,notebook/pro,PC,1.000000,1520000,0.05,Seoul,notebook,pro,1.000000,1.444000e+06,2026-01,VIP,2025-03-01
10,A011,C07,2026-01-23,desk/standing,FURNITURE,1.000000,380000,0.20,Busan,desk,standing,1.000000,3.040000e+05,2026-01,VIP,2025-01-10
11,A012,C04,2026-01-25,chair/basic,FURNITURE,1.000000,90000,0.00,Daegu,chair,basic,1.000000,9.000000e+04,2026-01,Gold,2025-11-20
12,A013,C08,2026-01-29,monitor/27inch,MONITOR,1.000000,350000,0.05,Incheon,monitor,27inch,1.000000,3.325000e+05,2026-01,Basic,2026-01-20
13,A014,C02,2026-02-01,mouse/basic,ACC,1.833333,25000,0.00,Busan,mouse,basic,1.833333,4.583333e+04,2026-02,Gold,2025-07-15
14,A015,C09,2026-02-03,notebook/pro,PC,1.000000,5000000,0.50,Seoul,notebook,pro,1.000000,2.500000e+06,2026-02,NaN,NaT
15,A016,C05,2026-02-04,desk/normal,FURNITURE,1.000000,220000,0.10,Daegu,desk,normal,1.000000,1.980000e+05,2026-02,Silver,2025-12-01
16,A017,C10,2026-02-07,keyboard/mechanical,ACC,1.833333,130000,0.10,Seoul,keyboard,mechanical,1.833333,2.145000e+05,2026-02,NaN,NaT
17,A018,C03,2026-02-10,chair/ergonomic,FURNITURE,1.000000,280000,0.15,Incheon,chair,ergonomic,1.000000,2.380000e+05,2026-02,Silver,2025-09-10

In [45]:
# 문제 8: 등급별 매출 분석
# order_customer에서 grade별 final_price 합계와 평균을 구하세요.
# grade가 없는 고객은 'Unknown'으로 채운 뒤 집계하세요.
# 결과는 grade_sales 변수에 저장하세요.

grade_sales = order_customer.fillna({"grade":"Unknown"}).groupby("grade")["final_price"].agg(["sum", "mean"])
grade_sales

              sum      mean
grade
Basic    415000.0  207500.0
Gold    1349500.0  269900.0
Silver  1434700.0  286940.0
VIP     3371000.0  842750.0

In [47]:
# 문제 9: 월별 매출 만들기
# order_date에서 주문 월을 추출해 order_month 컬럼을 만드세요.
# 월별 final_price 합계를 구하고 month_sales 변수에 저장하세요.
# 힌트: dt.to_period('M') 또는 dt.strftime('%Y-%m')를 사용할 수 있습니다.

orders["order_month"] = orders["order_date"].dt.strftime("%Y-%m")
month_sales = orders.groupby("order_month")["final_price"].sum()
month_sales

order_month
2026-01    6.088367e+06
2026-02    3.196333e+06
Name: final_price, dtype: float64

In [49]:
# 문제 10: 고액 주문 찾기
# final_price가 전체 final_price 평균보다 큰 주문만 필터링하세요.
# 결과는 high_value_orders 변수에 저장하세요.

print(orders[orders["final_price"] > orders["final_price"].mean()])

   order_id customer_id order_date       product category  quantity    price  \
0      A001         C01 2026-01-01  notebook/pro       PC       1.0  1500000
4      A005         C04 2026-01-08  notebook/air       PC       1.0  1100000
9      A010         C01 2026-01-22  notebook/pro       PC       1.0  1520000
14     A015         C09 2026-02-03  notebook/pro       PC       1.0  5000000

    discount_rate region product_main product_sub  filled_orders  final_price  \
0            0.05  Seoul     notebook         pro            1.0    1425000.0
4            0.03  Seoul     notebook         air            1.0    1067000.0
9            0.05  Seoul     notebook         pro            1.0    1444000.0
14           0.50  Seoul     notebook         pro            1.0    2500000.0

   order_month
0      2026-01
4      2026-01
9      2026-01
14     2026-02

In [59]:
# 문제 11: 고객별 구매 요약
# customer_id별 주문 횟수, 총 구매금액, 마지막 주문일을 구하세요.
# 컬럼명은 order_count, total_spent, last_order_date로 지정하세요.
# 결과는 customer_summary 변수에 저장하세요.

customer_summary = orders.groupby("customer_id")[["order_date", "final_price"]].agg(
  order_count=("final_price", "count"),
  total_spent=("final_price", "sum"),
  last_order_date=("order_date", "min")
)

In [65]:
# 문제 12: 실전 조합 문제
# customer_summary와 customers를 합쳐 고객별 grade, join_date, order_count, total_spent를 확인하세요.
# 주문 이력이 없는 고객도 포함되게 만드세요.
# order_count와 total_spent의 결측치는 0으로 채우세요.
# 결과는 customer_report 변수에 저장하세요.

pd.merge(customer_summary, customers, on="customer_id", how="outer")[["grade", "join_date", "order_count", "total_spent"]].fillna({"order_count": 0, "total_spent": 0})

     grade  join_date  order_count  total_spent
0      VIP 2025-03-01          3.0    3067000.0
1     Gold 2025-07-15          3.0     192500.0
2   Silver 2025-09-10          3.0    1007200.0
3     Gold 2025-11-20          2.0    1157000.0
4   Silver 2025-12-01          2.0     427500.0
5    Basic 2026-01-01          1.0      82500.0
6      VIP 2025-01-10          1.0     304000.0
7    Basic 2026-01-20          1.0     332500.0
8      NaN        NaT          1.0    2500000.0
9      NaN        NaT          1.0     214500.0
10    Gold 2025-08-08          0.0          0.0