In [1]:
import pandas as pd

df = pd.DataFrame({
    "age": [20, 25, 30, 35, None, 45],
    "salary": [2500, 3200, 4000, 4800, 5200, None],
    "city": ["Seoul", "Busan", "Seoul", "Incheon", "Busan", None],
    "purchased": [0, 0, 1, 1, 1, 0]
})

df

    age  salary     city  purchased
0  20.0  2500.0    Seoul          0
1  25.0  3200.0    Busan          0
2  30.0  4000.0    Seoul          1
3  35.0  4800.0  Incheon          1
4   NaN  5200.0    Busan          1
5  45.0     NaN      NaN          0

In [2]:
numeric_cols = ["age", "salary"]
categorical_cols = ["city"]

In [3]:
X = df.drop(columns=["purchased"])
y = df["purchased"]

In [4]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [13]:
from sklearn.preprocessing import OneHotEncoder

categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

In [14]:
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer([
    (
        "num",
        numeric_transformer,
        numeric_cols
    ),
    (
        "cat",
        categorical_transformer,
        categorical_cols
    )
])

In [16]:
X_transformed = preprocessor.fit_transform(X)
print(X_transformed)

[[-1.37799724 -1.59559181  0.          0.          1.        ]
 [-0.74199852 -0.82530611  1.          0.          0.        ]
 [-0.10599979  0.05502041  0.          0.          1.        ]
 [ 0.52999894  0.93534692  0.          1.          0.        ]
 [-0.10599979  1.37551018  1.          0.          0.        ]
 [ 1.8019964   0.05502041  1.          0.          0.        ]]

In [17]:
import pandas as pd

df = pd.DataFrame({
    "height": [165, 172, None, 180, 158, 175, 169, None],
    "weight": [60, 75, 68, None, 52, 80, 65, 70],
    "exercise": ["low", "high", "medium", "high", None, "medium", "low", "high"],
    "gender": ["M", "M", "F", "M", "F", "M", None, "F"],
    "healthy": [0, 1, 1, 1, 0, 1, 0, 1]
})

df

   height  weight exercise gender  healthy
0   165.0    60.0      low      M        0
1   172.0    75.0     high      M        1
2     NaN    68.0   medium      F        1
3   180.0     NaN     high      M        1
4   158.0    52.0      NaN      F        0
5   175.0    80.0   medium      M        1
6   169.0    65.0      low    NaN        0
7     NaN    70.0     high      F        1

In [22]:
X = df[df.drop(columns=["healthy"]).columns]
y = df["healthy"]
X, y

(   height  weight exercise gender
 0   165.0    60.0      low      M
 1   172.0    75.0     high      M
 2     NaN    68.0   medium      F
 3   180.0     NaN     high      M
 4   158.0    52.0      NaN      F
 5   175.0    80.0   medium      M
 6   169.0    65.0      low    NaN
 7     NaN    70.0     high      F,
 0    0
 1    1
 2    1
 3    1
 4    0
 5    1
 6    0
 7    1
 Name: healthy, dtype: int64)

In [23]:
numeric_cols = [
    "height",
    "weight"
]

categorical_cols = [
    "gender",
]

ordinal_cols = [
    "exercise"
]

In [19]:
# from sklearn.pipeline import Pipeline
# from sklearn.impute import SimpleImputer
# from sklearn.preprocessing import StandardScaler
# from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder

In [45]:
numeric_transformer = Pipeline([
    (
        "imputer",
        SimpleImputer(strategy="median")
    ),
    (
        "scaler",
        StandardScaler()
    )
])

categorical_transformer = Pipeline([
    (
        "imputer",
        SimpleImputer(strategy="most_frequent")
    ),
    (
        "onthot",
        OneHotEncoder(handle_unknown="ignore", sparse_output=False)
    )
])

ordinal_transformer = Pipeline([
    (
        "imputer",
        SimpleImputer(strategy="most_frequent")
    ),
    (
        "ordinal",
        OrdinalEncoder(
            handle_unknown="error",
            categories=[["low", "medium", "high"]]
        )
    )
])

In [46]:
preprocessor = ColumnTransformer([
    (
        "num",
        numeric_transformer,
        numeric_cols
    ),
    (
        "cat",
        categorical_transformer,
        categorical_cols
    ),
    (
        "ord",
        ordinal_transformer,
        ordinal_cols
    ),
])

In [48]:
# preprocessor.set_output(transform="default")
preprocessor.set_output(transform="pandas")
X_pre = preprocessor.fit_transform(X)
print(X_pre)

   num__height  num__weight  cat__gender_F  cat__gender_M  ord__exercise
0    -0.817178    -0.897958            0.0            1.0            0.0
1     0.326871     0.959886            0.0            1.0            2.0
2     0.081718     0.092892            1.0            0.0            1.0
3     1.634356     0.092892            0.0            1.0            2.0
4    -1.961227    -1.888807            1.0            0.0            2.0
5     0.817178     1.579167            0.0            1.0            1.0
6    -0.163436    -0.278677            0.0            1.0            0.0
7     0.081718     0.340605            1.0            0.0            2.0

In [36]:
preprocessor._columns

[['height', 'weight'], ['gender'], ['exercise']]

In [49]:
import pandas as pd

df = pd.DataFrame({
    "height": [
        165, 172, None, 180, 158, 175,
        169, None, 182, 160, 177, 168
    ],

    "weight": [
        60, 75, 68, None, 52, 80,
        65, 70, 85, 55, 77, 63
    ],

    "exercise": [
        "low", "high", "medium", "high",
        None, "medium", "low", "high",
        "high", "low", "medium", "low"
    ],

    "gender": [
        "M", "M", "F", "M",
        "F", "M", None, "F",
        "M", "F", "M", "F"
    ],

    "healthy": [
        0, 1, 1, 1,
        0, 1, 0, 1,
        1, 0, 1, 0
    ]
})

In [51]:
X_pre = preprocessor.fit_transform(X)
X_pre.head()

   num__height  num__weight  cat__gender_F  cat__gender_M  ord__exercise
0    -0.817178    -0.897958            0.0            1.0            0.0
1     0.326871     0.959886            0.0            1.0            2.0
2     0.081718     0.092892            1.0            0.0            1.0
3     1.634356     0.092892            0.0            1.0            2.0
4    -1.961227    -1.888807            1.0            0.0            2.0

In [56]:
from sklearn.linear_model import LogisticRegression

model = Pipeline([
    ("preprocessing", preprocessor),
    ("model", LogisticRegression(max_iter=20, n_jobs=-1))
])

In [57]:
model.fit(X, y)
model.score(X, y)

C:\LANG_CHAIN_2026\2026-05-19_KDT_lang_chain\workspace\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1457: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

1.0

In [58]:
X_val = pd.DataFrame({
    "height": [162, 178, 170, 185, 159, 173],
    "weight": [55, 82, 67, 88, 50, 72],
    "exercise": ["low", "high", "medium", "high", "low", "medium"],
    "gender": ["F", "M", "F", "M", "F", "M"]
})

y_val = pd.Series([
    0,
    1,
    1,
    1,
    0,
    1
])


model.score(X_val, y_val)

1.0

In [59]:
X_val.loc[0, "height"] = None
X_val.loc[2, "gender"] = None

model.predict(X_val)

array([0, 1, 1, 1, 0, 1])

In [61]:
df = pd.DataFrame({
    "age": [
        22, 31, 27, 45, None, 36,
        29, 52, 41, 25, 33, None
    ],
    "monthly_spend": [
        12000, 35000, 22000, 65000, 18000, None,
        28000, 72000, 51000, 15000, 39000, 26000
    ],
    "membership": [
        "basic", "standard", "basic", "premium",
        "standard", "premium", None, "premium",
        "standard", "basic", "standard", "basic"
    ],
    "region": [
        "Seoul", "Busan", "Seoul", "Incheon",
        "Busan", "Seoul", "Incheon", None,
        "Seoul", "Busan", "Incheon", "Seoul"
    ],
    "renewed": [
        0, 1, 0, 1,
        0, 1, 0, 1,
        1, 0, 1, 0
    ]
})

In [62]:
X = df.drop(columns=["renewed"])
y = df["renewed"]

In [63]:
# 결측값 요구사항: 중앙값
numeric_cols = [
    "age",
    "monthly_spend",
]
# 결측값 요구사항: 최빈값
categorical_cols = [
    "region"
]
# 결측값 요구사항: 최빈값
ordinal_cols = [
    "membership"
]

In [66]:
numeric_transformer = Pipeline([
    (
        "impute",
        SimpleImputer(strategy="median")
    ),
    (
        "scaler",
        StandardScaler()
    )
])

categorical_transformer = Pipeline([
    (
        "impute",
        SimpleImputer(strategy="most_frequent")
    ),
    (
        "onehot",
        OneHotEncoder(handle_unknown="ignore", sparse_output=False)
    )
])

ordinal_transformer = Pipeline([
    (
        "impute",
        SimpleImputer(strategy="most_frequent")
    ),
    (
        "ordinal",
        OrdinalEncoder(
            handle_unknown="error",
            categories=[["basic","standard", "premium"]]
        )
    )
])

In [70]:
preprocessor = ColumnTransformer([
    (
        "num",
        numeric_transformer,
        numeric_cols
    ),
    (
        "cat",
        categorical_transformer,
        categorical_cols
    ),
    (
        "ord",
        ordinal_transformer,
        ordinal_cols
    )
])

In [68]:
# preprocessor.set_output(transform="pandas")
# X_pre = preprocessor.fit_transform(X)
# X_pre

,num__age,num__monthly_spend,cat__region_Busan,cat__region_Incheon,cat__region_Seoul,ord__membership
0,-1.426427,-1.203692,0.0,0.0,1.0,0.0
1,-0.333845,0.040574,1.0,0.0,0.0,1.0
2,-0.819437,-0.662707,0.0,0.0,1.0,0.0
3,1.365728,1.663530,0.0,1.0,0.0,2.0
4,-0.212447,-0.879101,1.0,0.0,0.0,1.0
5,0.273146,-0.338116,0.0,0.0,1.0,2.0
6,-0.576641,-0.338116,0.0,1.0,0.0,0.0
7,2.215515,2.042219,0.0,0.0,1.0,2.0
8,0.880136,0.906150,0.0,0.0,1.0,1.0
9,-1.062233,-1.041397,1.0,0.0,0.0,0.0
10,-0.091049,0.256968,0.0,1.0,0.0,1.0
11,-0.212447,-0.446313,0.0,0.0,1.0,0.0

In [90]:
model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(max_iter=10))
])

In [91]:
model.fit(X, y)
model.score(X, y)

1.0

In [92]:
X_val = pd.DataFrame({
    "age": [24, 38, None, 49, 30],
    "monthly_spend": [14000, 43000, 25000, None, 32000],
    "membership": [
        "basic",
        "standard",
        "basic",
        "premium",
        "standard"
    ],
    "region": [
        "Seoul",
        "Busan",
        "Daegu",      # 학습 데이터에는 없던 값
        "Incheon",
        None
    ]
})

y_val = pd.Series([0, 1, 0, 1, 1])

model.score(X_val, y_val)

0.8

In [89]:
model.named_steps["model"].n_iter_

array([3], dtype=int32)