In [1]:
import pandas as pd

data = {
    "store": [
        "A", "A", "A", "B", "B", "B", "C", "C", "C", "A", "B", "C"
    ],
    "date": [
        "2026-06-01", "2026-06-02", "2026-06-03",
        "2026-06-01", "2026-06-02", "2026-06-03",
        "2026-06-01", "2026-06-02", "2026-06-03",
        "2026-06-04", "2026-06-04", "2026-06-04"
    ],
    "sales": [
        120, 150, 130,
        80, 95, 110,
        200, 180, 220,
        170, 105, 210
    ],
    "department": [
        "개발", "개발", "기획", "기획", "마케팅", "마케팅",
        "개발", "기획", "마케팅", "개발", "기획", "마케팅"
    ],
    "salary": [
        3200, 4500, 3000, 3800, 2800, 3500,
        5200, 4100, 3300, 4700, 3600, 3900
    ],
    "score": [
        95, 82, 77, 68, 55, 91,
        73, 88, 61, 100, 49, 84
    ],
    "region": [
        "서울", "서울", "부산", "부산", "서울", "대구",
        "대구", "서울", "부산", "대구", "서울", "부산"
    ],
    "category": [
        "전자", "식품", "전자", "의류", "의류", "전자",
        "식품", "전자", "식품", "의류", "식품", "전자"
    ],
    "profit": [
        30, 12, 25, 8, 15, 40,
        22, 35, 18, 10, 20, 28
    ],
    "email": [
        "a@test.com", "b@test.com", "a@test.com",
        "c@test.com", "d@test.com", "b@test.com",
        "e@test.com", "f@test.com", "c@test.com",
        "a@test.com", "e@test.com", "g@test.com"
    ],
    "created_at": [
        "2026-05-01 10:00", "2026-05-01 11:00", "2026-05-03 09:00",
        "2026-05-02 14:00", "2026-05-02 15:00", "2026-05-04 12:00",
        "2026-05-01 16:00", "2026-05-03 17:00", "2026-05-05 08:00",
        "2026-05-06 10:00", "2026-05-07 09:00", "2026-05-08 13:00"
    ]
}

df = pd.DataFrame(data)

df["date"] = pd.to_datetime(df["date"])
df["created_at"] = pd.to_datetime(df["created_at"])

df

,store,date,sales,department,salary,score,region,category,profit,email,created_at
0,A,2026-06-01,120,개발,3200,95,서울,전자,30,a@test.com,2026-05-01 10:00:00
1,A,2026-06-02,150,개발,4500,82,서울,식품,12,b@test.com,2026-05-01 11:00:00
2,A,2026-06-03,130,기획,3000,77,부산,전자,25,a@test.com,2026-05-03 09:00:00
3,B,2026-06-01,80,기획,3800,68,부산,의류,8,c@test.com,2026-05-02 14:00:00
4,B,2026-06-02,95,마케팅,2800,55,서울,의류,15,d@test.com,2026-05-02 15:00:00
5,B,2026-06-03,110,마케팅,3500,91,대구,전자,40,b@test.com,2026-05-04 12:00:00
6,C,2026-06-01,200,개발,5200,73,대구,식품,22,e@test.com,2026-05-01 16:00:00
7,C,2026-06-02,180,기획,4100,88,서울,전자,35,f@test.com,2026-05-03 17:00:00
8,C,2026-06-03,220,마케팅,3300,61,부산,식품,18,c@test.com,2026-05-05 08:00:00
9,A,2026-06-04,170,개발,4700,100,대구,의류,10,a@test.com,2026-05-06 10:00:00
10,B,2026-06-04,105,기획,3600,49,서울,식품,20,e@test.com,2026-05-07 09:00:00
11,C,2026-06-04,210,마케팅,3900,84,부산,전자,28,g@test.com,2026-05-08 13:00:00

In [4]:
df["prev_sales"] = df["sales"].shift(periods=1, axis=0)
df.head()
# df.info()

,store,date,sales,department,salary,score,region,category,profit,email,created_at,prev_sales
0,A,2026-06-01,120,개발,3200,95,서울,전자,30,a@test.com,2026-05-01 10:00:00,NaN
1,A,2026-06-02,150,개발,4500,82,서울,식품,12,b@test.com,2026-05-01 11:00:00,120.0
2,A,2026-06-03,130,기획,3000,77,부산,전자,25,a@test.com,2026-05-03 09:00:00,150.0
3,B,2026-06-01,80,기획,3800,68,부산,의류,8,c@test.com,2026-05-02 14:00:00,130.0
4,B,2026-06-02,95,마케팅,2800,55,서울,의류,15,d@test.com,2026-05-02 15:00:00,80.0

In [9]:
df["is_above_avg"] = df["salary"] > df.groupby("department")["salary"].transform("mean")

df.head()

,store,date,sales,department,salary,score,region,category,profit,email,created_at,prev_sales,is_above_avg
0,A,2026-06-01,120,개발,3200,95,서울,전자,30,a@test.com,2026-05-01 10:00:00,NaN,False
1,A,2026-06-02,150,개발,4500,82,서울,식품,12,b@test.com,2026-05-01 11:00:00,120.0,True
2,A,2026-06-03,130,기획,3000,77,부산,전자,25,a@test.com,2026-05-03 09:00:00,150.0,False
3,B,2026-06-01,80,기획,3800,68,부산,의류,8,c@test.com,2026-05-02 14:00:00,130.0,True
4,B,2026-06-02,95,마케팅,2800,55,서울,의류,15,d@test.com,2026-05-02 15:00:00,80.0,False

In [ ]:
pd.cut(
  df["score"], 
  bins=[0, 60, 70, 80, 90, 101], 
  labels=["F", "D", "C", "B", "A"], 
  right=False
)

0     A
1     B
2     C
3     D
4     F
5     A
6     C
7     B
8     D
9     A
10    F
11    B
Name: score, dtype: category
Categories (5, str): ['F' < 'D' < 'C' < 'B' < 'A']

In [18]:
df.pivot_table(
  index = "region",
  columns = "category",
  values=["profit"],
  aggfunc="mean",
  fill_value=0
)

         profit
category     식품    의류    전자
region
대구         22.0  10.0  40.0
부산         18.0   8.0  26.5
서울         16.0  15.0  32.5

In [20]:
df.sort_values(by="created_at").drop_duplicates(subset="email", keep="last")

,store,date,sales,department,salary,score,region,category,profit,email,created_at,prev_sales,is_above_avg
4,B,2026-06-02,95,마케팅,2800,55,서울,의류,15,d@test.com,2026-05-02 15:00:00,80.0,False
7,C,2026-06-02,180,기획,4100,88,서울,전자,35,f@test.com,2026-05-03 17:00:00,200.0,True
5,B,2026-06-03,110,마케팅,3500,91,대구,전자,40,b@test.com,2026-05-04 12:00:00,95.0,True
8,C,2026-06-03,220,마케팅,3300,61,부산,식품,18,c@test.com,2026-05-05 08:00:00,180.0,False
9,A,2026-06-04,170,개발,4700,100,대구,의류,10,a@test.com,2026-05-06 10:00:00,220.0,True
10,B,2026-06-04,105,기획,3600,49,서울,식품,20,e@test.com,2026-05-07 09:00:00,170.0,False
11,C,2026-06-04,210,마케팅,3900,84,부산,전자,28,g@test.com,2026-05-08 13:00:00,105.0,True

In [34]:
pd.concat([
  df[["store", "date", "sales"]],
  df.sort_values(["store", "date"], ascending=True).groupby("store")["sales"].cumsum().rename("cumsum_sales")
], axis=1).pivot_table(
  index="store",
  columns="date",
  values="cumsum_sales",
  aggfunc="first"
)

date   2026-06-01  2026-06-02  2026-06-03  2026-06-04
store
A             120         270         400         570
B              80         175         285         390
C             200         380         600         810

In [40]:
pd.concat([
  df[["department", "salary"]],
  df.groupby(["department"])["salary"].rank(method="dense", ascending=False).rename("salary_rank")
], axis=1).sort_values(["department", "salary_rank"])

   department  salary  salary_rank
6          개발    5200          1.0
9          개발    4700          2.0
1          개발    4500          3.0
0          개발    3200          4.0
7          기획    4100          1.0
3          기획    3800          2.0
10         기획    3600          3.0
2          기획    3000          4.0
11        마케팅    3900          1.0
5         마케팅    3500          2.0
8         마케팅    3300          3.0
4         마케팅    2800          4.0

In [45]:
import numpy as np

condlist = [
  ((df["sales"] >= 180) & (df["profit"] >= 30)),
  ((df["sales"] >= 120) & (df["profit"] >= 15)),
]

choices = ["high", "middle"]

pd.concat([
  df, 
  pd.Series(np.select(
    condlist,
    choices,
    default="low"
  ), name="performance")
], axis=1)

,store,date,sales,department,salary,score,region,category,profit,email,created_at,prev_sales,is_above_avg,performance
0,A,2026-06-01,120,개발,3200,95,서울,전자,30,a@test.com,2026-05-01 10:00:00,NaN,False,middle
1,A,2026-06-02,150,개발,4500,82,서울,식품,12,b@test.com,2026-05-01 11:00:00,120.0,True,low
2,A,2026-06-03,130,기획,3000,77,부산,전자,25,a@test.com,2026-05-03 09:00:00,150.0,False,middle
3,B,2026-06-01,80,기획,3800,68,부산,의류,8,c@test.com,2026-05-02 14:00:00,130.0,True,low
4,B,2026-06-02,95,마케팅,2800,55,서울,의류,15,d@test.com,2026-05-02 15:00:00,80.0,False,low
5,B,2026-06-03,110,마케팅,3500,91,대구,전자,40,b@test.com,2026-05-04 12:00:00,95.0,True,low
6,C,2026-06-01,200,개발,5200,73,대구,식품,22,e@test.com,2026-05-01 16:00:00,110.0,True,middle
7,C,2026-06-02,180,기획,4100,88,서울,전자,35,f@test.com,2026-05-03 17:00:00,200.0,True,high
8,C,2026-06-03,220,마케팅,3300,61,부산,식품,18,c@test.com,2026-05-05 08:00:00,180.0,False,middle
9,A,2026-06-04,170,개발,4700,100,대구,의류,10,a@test.com,2026-05-06 10:00:00,220.0,True,low
10,B,2026-06-04,105,기획,3600,49,서울,식품,20,e@test.com,2026-05-07 09:00:00,170.0,False,low
11,C,2026-06-04,210,마케팅,3900,84,부산,전자,28,g@test.com,2026-05-08 13:00:00,105.0,True,middle

In [46]:
df[df["email"].str.endswith("test.com")]

,store,date,sales,department,salary,score,region,category,profit,email,created_at,prev_sales,is_above_avg
0,A,2026-06-01,120,개발,3200,95,서울,전자,30,a@test.com,2026-05-01 10:00:00,NaN,False
1,A,2026-06-02,150,개발,4500,82,서울,식품,12,b@test.com,2026-05-01 11:00:00,120.0,True
2,A,2026-06-03,130,기획,3000,77,부산,전자,25,a@test.com,2026-05-03 09:00:00,150.0,False
3,B,2026-06-01,80,기획,3800,68,부산,의류,8,c@test.com,2026-05-02 14:00:00,130.0,True
4,B,2026-06-02,95,마케팅,2800,55,서울,의류,15,d@test.com,2026-05-02 15:00:00,80.0,False
5,B,2026-06-03,110,마케팅,3500,91,대구,전자,40,b@test.com,2026-05-04 12:00:00,95.0,True
6,C,2026-06-01,200,개발,5200,73,대구,식품,22,e@test.com,2026-05-01 16:00:00,110.0,True
7,C,2026-06-02,180,기획,4100,88,서울,전자,35,f@test.com,2026-05-03 17:00:00,200.0,True
8,C,2026-06-03,220,마케팅,3300,61,부산,식품,18,c@test.com,2026-05-05 08:00:00,180.0,False
9,A,2026-06-04,170,개발,4700,100,대구,의류,10,a@test.com,2026-05-06 10:00:00,220.0,True
10,B,2026-06-04,105,기획,3600,49,서울,식품,20,e@test.com,2026-05-07 09:00:00,170.0,False
11,C,2026-06-04,210,마케팅,3900,84,부산,전자,28,g@test.com,2026-05-08 13:00:00,105.0,True

In [70]:
# df["email"].str.split("@").map(lambda x: x[-1]).unique()
# df["email"].str.split("@").str.get(1).unique()
df["email"].str.rsplit("@", n=1).str[-1].unique()

array(['test.com'], dtype=object)

In [77]:
pd.concat([
  df["created_at"],
  df["created_at"].dt.day_name()
], axis=1)

            created_at created_at
0  2026-05-01 10:00:00     Friday
1  2026-05-01 11:00:00     Friday
2  2026-05-03 09:00:00     Sunday
3  2026-05-02 14:00:00   Saturday
4  2026-05-02 15:00:00   Saturday
5  2026-05-04 12:00:00     Monday
6  2026-05-01 16:00:00     Friday
7  2026-05-03 17:00:00     Sunday
8  2026-05-05 08:00:00    Tuesday
9  2026-05-06 10:00:00  Wednesday
10 2026-05-07 09:00:00   Thursday
11 2026-05-08 13:00:00     Friday

In [79]:
df.groupby("date")["sales"].sum()
df.set_index("date").resample("D")["sales"].sum()

date
2026-06-01    400
2026-06-02    425
2026-06-03    460
2026-06-04    485
Freq: D, Name: sales, dtype: int64

In [89]:
df.sort_values(["store", "date"]).groupby("store")["sales"].rolling(2, min_periods=1).mean().reset_index()

   store  level_1  sales
0      A        0  120.0
1      A        1  135.0
2      A        2  140.0
3      A        9  150.0
4      B        3   80.0
5      B        4   87.5
6      B        5  102.5
7      B       10  107.5
8      C        6  200.0
9      C        7  190.0
10     C        8  200.0
11     C       11  215.0

In [105]:
df.groupby("store")[["sales", "created_at"]].mean(skipna=True)

       sales          created_at
store
A      142.5 2026-05-03 04:00:00
B       97.5 2026-05-04 06:30:00
C      202.5 2026-05-04 19:30:00

In [106]:
df.sort_values(["store", "date"]).groupby("store")["sales"].pct_change().rename("sales_growth")

0          NaN
1     0.250000
2    -0.133333
9     0.307692
3          NaN
4     0.187500
5     0.157895
10   -0.045455
6          NaN
7    -0.100000
8     0.222222
11   -0.045455
Name: sales_growth, dtype: float64