In [2]:
import pandas as pd

In [3]:
import pathlib

In [4]:
pathlib.Path()

WindowsPath('.')

In [5]:
df = pd.read_csv("../../../resource/class/advertise_model_brand_score.csv")
df

     이름          소속사 성별        생년월일        키  혈액형    브랜드평판지수
0   변우석     바로엔터테인먼트  남  1991-10-31  190.3cm    B  3,762,141
1   임영웅        물고기뮤직  남  1991-06-16  182.2cm    A  3,349,309
2   손흥민    로스앤젤레스 FC  남  1992-07-08    183cm   AB  3,067,512
3   박지훈     YY엔터테인먼트  남  1999-05-29    173cm   AB  2,831,201
4   유재석          안테나  남  1972-08-14    178cm    B  2,015,312
5   김연아        올댓스포츠  여  1990-09-05    164cm    O  1,085,281
6   이정후  샌프란시스코 자이언츠  남  1998-08-20    185cm    A  1,015,456
7   고윤정          MAA  여  1996-04-22    163cm    B    855,724
8   김혜윤      아티스트컴퍼니  여  1996-11-10    160cm    B    831,169
9   이정재      아티스트컴퍼니  남  1972-12-15    180cm    B    664,985
10  마동석    빅펀치엔터테인먼트  남  1971-03-01    178cm    O    651,035
11   공유      매니지먼트 숲  남  1979-07-10    184cm    A    561,519
12  이준호    JYP엔터테인먼트  남  1990-01-25    178cm    A    543,485
13  이찬원     티엔엔터테인먼트  남  1996-11-01    176cm    B    486,700
14  김도영     KIA 타이거즈  남  2003-10-02    183cm  NaN    481,761
15  박보검       더블랙레이블  남  1993-06-16    182cm    O    451,540
16  엄태구          팀호프  남  1983-11-09    181cm    O    380,064
17  구교환        나무엑터스  남  1982-12-14    182cm    A    371,673
18  지예은    S&A엔터테인먼트  여  1994-07-26    171cm  NaN    370,543
19  전지현       이음해시태그  여  1981-10-30    173cm    B    358,271

In [6]:
type(df)

pandas.DataFrame

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   이름       20 non-null     str
 1   소속사      20 non-null     str
 2   성별       20 non-null     str
 3   생년월일     20 non-null     str
 4   키        20 non-null     str
 5   혈액형      18 non-null     str
 6   브랜드평판지수  20 non-null     str
dtypes: str(7)
memory usage: 1.2 KB

In [8]:
isna_columns = df.columns[df.isna().sum() >= 1]
print(isna_columns.to_numpy())
# print(df.info())

# 14와 18번 행 사라짐 (혈액형)
df.dropna(axis=0, subset=isna_columns)

['혈액형']

     이름          소속사 성별        생년월일        키 혈액형    브랜드평판지수
0   변우석     바로엔터테인먼트  남  1991-10-31  190.3cm   B  3,762,141
1   임영웅        물고기뮤직  남  1991-06-16  182.2cm   A  3,349,309
2   손흥민    로스앤젤레스 FC  남  1992-07-08    183cm  AB  3,067,512
3   박지훈     YY엔터테인먼트  남  1999-05-29    173cm  AB  2,831,201
4   유재석          안테나  남  1972-08-14    178cm   B  2,015,312
5   김연아        올댓스포츠  여  1990-09-05    164cm   O  1,085,281
6   이정후  샌프란시스코 자이언츠  남  1998-08-20    185cm   A  1,015,456
7   고윤정          MAA  여  1996-04-22    163cm   B    855,724
8   김혜윤      아티스트컴퍼니  여  1996-11-10    160cm   B    831,169
9   이정재      아티스트컴퍼니  남  1972-12-15    180cm   B    664,985
10  마동석    빅펀치엔터테인먼트  남  1971-03-01    178cm   O    651,035
11   공유      매니지먼트 숲  남  1979-07-10    184cm   A    561,519
12  이준호    JYP엔터테인먼트  남  1990-01-25    178cm   A    543,485
13  이찬원     티엔엔터테인먼트  남  1996-11-01    176cm   B    486,700
15  박보검       더블랙레이블  남  1993-06-16    182cm   O    451,540
16  엄태구          팀호프  남  1983-11-09    181cm   O    380,064
17  구교환        나무엑터스  남  1982-12-14    182cm   A    371,673
19  전지현       이음해시태그  여  1981-10-30    173cm   B    358,271

In [9]:
df.describe()

         이름      소속사  성별        생년월일      키 혈액형    브랜드평판지수
count    20       20  20          20     20  18         20
unique   20       19   2          20     15   4         20
top     변우석  아티스트컴퍼니   남  1991-10-31  178cm   B  3,762,141
freq      1        2  15           1      3   7          1

In [10]:
pd.DataFrame(df.values)

      0            1  2           3        4    5          6
0   변우석     바로엔터테인먼트  남  1991-10-31  190.3cm    B  3,762,141
1   임영웅        물고기뮤직  남  1991-06-16  182.2cm    A  3,349,309
2   손흥민    로스앤젤레스 FC  남  1992-07-08    183cm   AB  3,067,512
3   박지훈     YY엔터테인먼트  남  1999-05-29    173cm   AB  2,831,201
4   유재석          안테나  남  1972-08-14    178cm    B  2,015,312
5   김연아        올댓스포츠  여  1990-09-05    164cm    O  1,085,281
6   이정후  샌프란시스코 자이언츠  남  1998-08-20    185cm    A  1,015,456
7   고윤정          MAA  여  1996-04-22    163cm    B    855,724
8   김혜윤      아티스트컴퍼니  여  1996-11-10    160cm    B    831,169
9   이정재      아티스트컴퍼니  남  1972-12-15    180cm    B    664,985
10  마동석    빅펀치엔터테인먼트  남  1971-03-01    178cm    O    651,035
11   공유      매니지먼트 숲  남  1979-07-10    184cm    A    561,519
12  이준호    JYP엔터테인먼트  남  1990-01-25    178cm    A    543,485
13  이찬원     티엔엔터테인먼트  남  1996-11-01    176cm    B    486,700
14  김도영     KIA 타이거즈  남  2003-10-02    183cm  NaN    481,761
15  박보검       더블랙레이블  남  1993-06-16    182cm    O    451,540
16  엄태구          팀호프  남  1983-11-09    181cm    O    380,064
17  구교환        나무엑터스  남  1982-12-14    182cm    A    371,673
18  지예은    S&A엔터테인먼트  여  1994-07-26    171cm  NaN    370,543
19  전지현       이음해시태그  여  1981-10-30    173cm    B    358,271

In [11]:
print(type(df.columns))
print(df.columns)

<class 'pandas.Index'>
Index(['이름', '소속사', '성별', '생년월일', '키', '혈액형', '브랜드평판지수'], dtype='str')

In [12]:
df["int_height"] = df["키"].str.replace(r"[^0-9.]", "", regex=True).astype(float)

In [13]:
df = df.rename(columns = {
  "int_height": "float_height"
})

df

     이름          소속사 성별        생년월일        키  혈액형    브랜드평판지수  float_height
0   변우석     바로엔터테인먼트  남  1991-10-31  190.3cm    B  3,762,141         190.3
1   임영웅        물고기뮤직  남  1991-06-16  182.2cm    A  3,349,309         182.2
2   손흥민    로스앤젤레스 FC  남  1992-07-08    183cm   AB  3,067,512         183.0
3   박지훈     YY엔터테인먼트  남  1999-05-29    173cm   AB  2,831,201         173.0
4   유재석          안테나  남  1972-08-14    178cm    B  2,015,312         178.0
5   김연아        올댓스포츠  여  1990-09-05    164cm    O  1,085,281         164.0
6   이정후  샌프란시스코 자이언츠  남  1998-08-20    185cm    A  1,015,456         185.0
7   고윤정          MAA  여  1996-04-22    163cm    B    855,724         163.0
8   김혜윤      아티스트컴퍼니  여  1996-11-10    160cm    B    831,169         160.0
9   이정재      아티스트컴퍼니  남  1972-12-15    180cm    B    664,985         180.0
10  마동석    빅펀치엔터테인먼트  남  1971-03-01    178cm    O    651,035         178.0
11   공유      매니지먼트 숲  남  1979-07-10    184cm    A    561,519         184.0
12  이준호    JYP엔터테인먼트  남  1990-01-25    178cm    A    543,485         178.0
13  이찬원     티엔엔터테인먼트  남  1996-11-01    176cm    B    486,700         176.0
14  김도영     KIA 타이거즈  남  2003-10-02    183cm  NaN    481,761         183.0
15  박보검       더블랙레이블  남  1993-06-16    182cm    O    451,540         182.0
16  엄태구          팀호프  남  1983-11-09    181cm    O    380,064         181.0
17  구교환        나무엑터스  남  1982-12-14    182cm    A    371,673         182.0
18  지예은    S&A엔터테인먼트  여  1994-07-26    171cm  NaN    370,543         171.0
19  전지현       이음해시태그  여  1981-10-30    173cm    B    358,271         173.0

In [15]:
df["brand"] = df["브랜드평판지수"].str.replace(",", "").astype(int)
df_standard = df[["float_height", "brand"]]

df = df.drop(["brand", "float_height"], axis=1)

In [19]:
print(df.head(2))
print(df_standard.head(2))

cc = pd.concat([df, df_standard], axis=1)
cc.head()

    이름       소속사 성별        생년월일        키 혈액형    브랜드평판지수
0  변우석  바로엔터테인먼트  남  1991-10-31  190.3cm   B  3,762,141
1  임영웅     물고기뮤직  남  1991-06-16  182.2cm   A  3,349,309
   float_height    brand
0         190.3  3762141
1         182.2  3349309

,이름,소속사,성별,생년월일,키,혈액형,브랜드평판지수,float_height,brand
0,변우석,바로엔터테인먼트,남,1991-10-31,190.3cm,B,"3,762,141",190.3,3762141
1,임영웅,물고기뮤직,남,1991-06-16,182.2cm,A,"3,349,309",182.2,3349309
2,손흥민,로스앤젤레스 FC,남,1992-07-08,183cm,AB,"3,067,512",183.0,3067512
3,박지훈,YY엔터테인먼트,남,1999-05-29,173cm,AB,"2,831,201",173.0,2831201
4,유재석,안테나,남,1972-08-14,178cm,B,"2,015,312",178.0,2015312

In [20]:
cc.describe()

       float_height         brand
count     20.000000  2.000000e+01
mean     177.325000  1.206734e+06
std        7.906751  1.125405e+06
min      160.000000  3.582710e+05
25%      173.000000  4.742058e+05
50%      179.000000  6.580100e+05
75%      182.400000  1.317789e+06
max      190.300000  3.762141e+06